import os.path

top = '.'
out = 'build'


def options(ctx):
    ctx.load('pebble_sdk')


def configure(ctx):
    ctx.load('pebble_sdk')


def build(ctx):
    ctx.load('pebble_sdk')

    binaries = []
    cached_env = ctx.env
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf = '{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        shared = ctx.path.find_node('../../shared/appmessage/watch')
        errors = ctx.path.find_node('../../shared/errors/watch')
        sources = ctx.path.ant_glob('src/c/**/*.c') + shared.ant_glob('*.c') + errors.ant_glob('*.c')
        ctx.pbl_build(
            source=sources,
            includes=[shared.abspath(), errors.abspath()],
            target=app_elf,
            bin_type='app'
        )
        binaries.append({'platform': platform, 'app_elf': app_elf})

    ctx.env = cached_env
    ctx.set_group('bundle')
    shared_js = ctx.path.find_node('../../shared/appmessage/pkjs')
    errors_js = ctx.path.find_node('../../shared/errors/pkjs')
    ctx.pbl_bundle(
        binaries=binaries,
        js=ctx.path.ant_glob(['src/pkjs/**/*.js', 'src/common/**/*.js']) + shared_js.ant_glob('*.js') + errors_js.ant_glob('*.js'),
        js_entry_file='src/pkjs/index.js'
    )
